version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  homepage-config-gui:
    build: .
    container_name: homepage-config-gui
    ports:
      - "3001:3000"
    volumes:
      - ./config:/app/config:rw  # Share config with homepage
    restart: unless-stopped
    depends_on:
      - homepage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.config.rule=Host(`config.yourdomain.com`)"
