name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./homepage-config-gui
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: homepage-config-gui/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --coverage --ci --passWithNoTests --watchAll=false

    - name: Build application
      run: npm run build

    - name: Test Docker build (Live)
      run: |
        docker build -t homepage-config-gui:test .
        docker run --rm -d --name test-live -p 3001:3001 homepage-config-gui:test
        sleep 10
        curl -f http://localhost:3001/api/health || exit 1
        docker stop test-live

    - name: Test Docker build (Static)
      run: |
        docker build -f Dockerfile.static -t homepage-config-gui:static-test .
        docker run --rm -d --name test-static -p 8080:80 homepage-config-gui:static-test
        sleep 5
        curl -f http://localhost:8080/ || exit 1
        docker stop test-static

  docker-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./homepage-config-gui
        file: ./homepage-config-gui/Dockerfile
        push: false
        tags: homepage-config-gui:ci-test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        docker run --rm -d --name test-container -p 3001:3001 homepage-config-gui:ci-test
        sleep 10
        curl -f http://localhost:3001/api/health || exit 1
        docker stop test-container