name: Debug Docker Build

on:
  workflow_dispatch: # Manual trigger only

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List files in root
      run: |
        echo "=== Root directory ==="
        ls -la
        echo "=== homepage-config-gui directory ==="
        ls -la homepage-config-gui/

    - name: Check Dockerfile
      run: |
        echo "=== Dockerfile content ==="
        head -20 homepage-config-gui/Dockerfile
        echo "=== Dockerfile.static content ==="
        head -20 homepage-config-gui/Dockerfile.static

    - name: Check package.json
      run: |
        echo "=== package.json content ==="
        head -20 homepage-config-gui/package.json

  test-build-basic:
    runs-on: ubuntu-latest
    needs: debug
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test build (no push)
      run: |
        cd homepage-config-gui
        docker build -t test:local .