name: Isolated Build (No Workspace)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy homepage-config-gui to isolated directory
      run: |
        cp -r homepage-config-gui /tmp/isolated-build
        cd /tmp/isolated-build
        ls -la

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install and build in isolated directory
      run: |
        cd /tmp/isolated-build
        # Now we're completely outside the workspace
        NODE_OPTIONS="--max_old_space_size=1536" npm install --no-fund --no-audit --prefer-offline
        npm cache clean --force
        NODE_OPTIONS="--max_old_space_size=1536" npm run build
        ls -la build/

    - name: Copy build back to workspace
      run: |
        cp -r /tmp/isolated-build/build homepage-config-gui/
        ls -la homepage-config-gui/build/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: hoiber
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./homepage-config-gui
        push: true
        platforms: linux/amd64
        tags: |
          hoiber/homepage-config-editor:latest
          hoiber/homepage-config-editor:static
        file-inline: |
          FROM nginx:alpine
          COPY build /usr/share/nginx/html
          COPY nginx.conf /etc/nginx/nginx.conf
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]