name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./homepage-config-gui
        file: ./homepage-config-gui/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Homepage Config GUI Release ${{ github.ref_name }}
          
          ### 🚀 Features
          - Visual configuration builder for Homepage
          - Live YAML file updates
          - 131+ pre-configured services
          - 100+ widget types
          - Docker integration with multiple profiles
          
          ### 🐳 Docker Images
          - `ghcr.io/${{ github.repository }}:${{ github.ref_name }}` (Live updates)
          - `ghcr.io/${{ github.repository }}:latest` (Latest stable)
          
          ### 📖 Documentation
          See README.md for installation and usage instructions.
        draft: false
        prerelease: false
