name: Simple Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: homepage-config-gui
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: homepage-config-gui/package-lock.json

    - name: Install dependencies
      run: npm ci --no-audit --no-fund

    - name: Build React app
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: hoiber
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./homepage-config-gui
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          hoiber/homepage-config-editor:latest
          hoiber/homepage-config-editor:static
        file-inline: |
          FROM nginx:alpine
          COPY build /usr/share/nginx/html
          COPY nginx.conf /etc/nginx/nginx.conf
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]